# Copyright (c) 2020-2026 by Miguel Caro and Tigany Zarrouk

# This is an important note for those building TurboGAP on CSC's Mahti
# supercomputer with this Makefile. Before compiling, make sure you have
# loaded the correct module environment:
#
#  module load gcc/15.2.0 openmpi/5.0.10 openblas/0.3.30
#
#
# We you run TurboGAP, make sure to load this same environment at the top
# of your Slurm submission script.

# User-modifiable variables below

# Compiler, preprocessor directives, etc.
F90=mpif90
PP=-cpp -D _MPIF90
F90_MOD_DIR_OPT=-J


# Optimization flags
F90_OPTS=-fPIC -O3 -march=znver5
# For a debug build use `make DEBUG=1`, which appends -O0 -g -fbacktrace
# -fcheck=all to whatever this line sets and puts the result in build-dbg/
# and bin-dbg/. Editing this line instead reuses the same object tree, so
# make rebuilds only what changed and links the rest of the optimised
# objects -- and afterwards bin/turbogap is a mixture with nothing to say so.

# BLAS and LAPACK libraries
LIBS=-lopenblas
