# Copyright (c) 2020-2026 by Miguel Caro and Tigany Zarrouk

# This is an important note for those building TurboGAP on CSC's Mahti
# supercomputer with this Makefile. Before compiling, make sure you have
# loaded the correct module environment:
#
#  module load gcc/15.2.0 openmpi/5.0.10 openblas/0.3.30     
#     
#
# We you run TurboGAP, make sure to load this same environment at the top
# of your Slurm submission script.

# User-modifiable variables below

# Compiler, preprocessor directives, etc.
F90=mpif90
PP=-cpp -D _MPIF90
F90_MOD_DIR_OPT=-J


# Optimization flags (uncomment second option to enable debugging tools)
F90_OPTS=-fPIC -O3 -march=znver5
#F90_OPTS=-fPIC -O3 -fcheck=bounds -g -fcheck=all -Wall

# BLAS and LAPACK libraries
LIBS=-lopenblas
