# Copyright (c) 2020-2021 by Albert Bartók and Miguel Caro

# This is an important note for those building TurboGAP on CSC's Puhti
# supercomputer with this Makefile. Before compiling, make sure you have
# loaded the correct module environment:
#
#     module reset
#     module load gcc/11.3.0
#
# We you run TurboGAP, make sure to load this same environment at the top
# of your Slurm submission script.

# User-modifiable variables below

# Compiler, preprocessor directives, etc.
F90=mpif90
PP=-cpp -D _MPIF90
F90_MOD_DIR_OPT=-J

# Optimization flags (uncomment second option to enable debugging tools)
F90_OPTS=-fPIC -O3
#F90_OPTS=-fPIC -O3 -fcheck=bounds -g -fcheck=all -Wall

# BLAS and LAPACK libraries from Intel MKL
LIBS=-lmkl_gf_lp64 -lmkl_sequential -lmkl_core
