# Copyright (c) 2020-2021 by Albert Bartók and Miguel Caro

# User-modifiable variables below

# Compiler, preprocessor directives, etc.
F90=mpif90
PP=-cpp -D _MPIF90
F90_MOD_DIR_OPT=-J

# Optimization flags (uncomment second option to enable debugging tools)
#F90_OPTS=-fPIC -O3
F90_OPTS=-fPIC -O0 -fcheck=bounds -g -fcheck=all -Wall #-ffpe-trap=invalid

# BLAS and LAPACK libraries
LIBS=-llapack -lblas
#LAPACK_LIB_DIR=
#LIBS=-L$(LAPACK_LIB_DIR) -llapack -lblas
