# Copyright (c) 2020-2021 by Albert Bartók and Miguel Caro

# This is an important note for those building TurboGAP on CSC's Mahti
# supercomputer with this Makefile. Before compiling, make sure you have
# loaded the correct module environment:
#
#     module reset
#     module load gcc
#     module load openblas
#     module load openmpi
#     module load cuda
#
# When you run TurboGAP, make sure to load this same environment at the top
# of your Slurm submission script.

# User-modifiable variables below

# Compiler, preprocessor directives, etc.
F90=mpif90
CU=nvcc
PP=-cpp -D _MPIF90
F90_MOD_DIR_OPT=-J

# Optimization flags (uncomment second option to enable debugging tools)
F90_OPTS=-fPIC -O2 -lcudart   -lcublas -lcurand 
CUDA_OPTS= -lcublas -lcurand -arch=sm_80 
#F90_OPTS+=-fPIC -O3 -fcheck=bounds -g -fcheck=all -Wall

# BLAS and LAPACK libraries
LIBS= -lopenblas
