! Generated by tools/keyword_docs.py from src/read_files.f90 and
! src/types.f90. Do not edit: edit the !> block above the keyword in
! src/read_files.f90 and run `make docs`.

module keyword_help

   implicit none

   private
   public :: print_keyword_help, keyword_help_topics

contains

!  What `turbogap --help <topic>` accepts, for the error message.
   function keyword_help_topics() result(text)
      character(len=64) :: text
      text = 'predict/md/mc/soap/gap'
   end function keyword_help_topics

!  Print the keyword reference. An empty topic prints everything; a mode
!  prints the input-file keywords that do something in it; "gap" prints
!  the potential-file keywords instead.
   subroutine print_keyword_help(topic)

      character(len=*), intent(in) :: topic

      logical :: every
      logical :: gap_only
      character(len=len(topic)) :: mode

      every = (len_trim(topic) == 0)
      gap_only = (topic == 'gap')
!     A mode never selects the potential file, so blank it out there and
!     the per-keyword guards below need no second variable.
      mode = topic
      if (gap_only) mode = ''

      write (*, '(A)') 'TurboGAP keywords'
      write (*, '(A)') ''
      if (every) then
         write (*, '(A)') '  Everything. `turbogap --help <predict|md|mc|soap|gap>` narrows this down.'
      else if (gap_only) then
         write (*, '(A)') '  Keywords of the potential (.gap) file.'
      else
         write (*, '(A)') '  Input-file keywords that do something in mode: '//trim(topic)
      end if
      write (*, '(A)') ''
      write (*, '(A)') '  Full reference, with the cross-references: docs/keywords.html'
      write (*, '(A)') ''

!  ======== the input file
      if (every .or. .not. gap_only) then
         write (*, '(A)') ''
         write (*, '(A)') '##### KEYWORDS FOR THE INPUT FILE #####'
         write (*, '(A)') ''
         write (*, '(A)') '  One keyword = value per line. A keyword this list does not contain'
         write (*, '(A)') '  aborts the run.'
         write (*, '(A)') ''
      end if

!     ---- General
      if (every .or. .not. gap_only) then
         write (*, '(A)') '=== GENERAL ==='
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  atoms_file (or input_file)           [string]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  e0                                   [real list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  gpu_mem_fraction                     [real, default 0.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  masses                               [real list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  max_gbytes_per_process               [real, default 1.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  neighbors_buffer                     [real, default 0.25]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  radii                                [real list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  random_seed                          [integer, default 0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  species                              [string list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  timing                               [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  verbosity (or verb)                  [integer, default 0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  which_atom                           [integer, default 0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if

!     ---- Run control
      if (every .or. .not. gap_only) then
         write (*, '(A)') '=== RUN CONTROL ==='
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  do_derivatives                       [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  do_derivatives_fd                    [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  do_forces                            [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  do_mc                                [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  do_md                                [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  do_prediction                        [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  e_tol                                [real, default 1.e-6]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  f_tol                                [real, default 0.01]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  gamma0                               [real, default 0.01]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  max_opt_step                         [real, default 0.1]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  max_opt_step_eps                     [real, default 0.05]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  optimize                             [string, default vv]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  p_tol                                [real, default 0.01]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  target_pos_step                      [real]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets variable_time_step'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  tau_dt                               [real, default 100.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  write_derivatives                    [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  write_soap                           [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if

!     ---- Molecular dynamics
      if (every .or. .not. gap_only) then
         write (*, '(A)') '=== MOLECULAR DYNAMICS ==='
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  barostat                             [string, default none]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  barostat_sym                         [string, default isotropic]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  box_scaling_factor                   [real(3, 3), default identity]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  gamma_p                              [real, default 1.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  md_nsteps                            [integer, default 1]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  md_step                              [real, default 1.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  n_t_hold                             [integer, default 0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets t_hold'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  p_beg                                [real, default 1.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  p_end                                [real, default 1.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  scale_box                            [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  t_beg                                [real, default 300.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  t_end                                [real, default 300.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  t_hold                               [real list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets n_t_hold'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  tau_p                                [real, default 1000.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  tau_t                                [real, default 100.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  thermostat                           [string, default none]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if

!     ---- Nested sampling
      if (every .or. .not. gap_only) then
         write (*, '(A)') '=== NESTED SAMPLING ==='
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  n_nested                             [integer, default 0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets do_nested_sampling'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  nested_max_strain                    [real, default 0.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  nested_max_volume_change             [real, default 0.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  p_nested                             [real, default 0.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  scale_box_nested                     [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if

!     ---- Monte Carlo
      if (every .or. .not. gap_only) then
         write (*, '(A)') '=== MONTE CARLO ==='
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  accessible_volume                    [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  mc_acceptance                        [real list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets mc_types'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  mc_hamiltonian                       [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  mc_hybrid_opt                        [string, default vv]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  mc_lnvol_max                         [real, default 0.01]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  mc_min_dist                          [real, default 0.2]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  mc_move_max                          [real, default 1.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  mc_mu                                [real list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets n_mc_mu'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  mc_mu_acceptance                     [real list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets mc_mu'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  mc_nrelax                            [integer, default 0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  mc_nsteps                            [integer, default 1]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  mc_optimize_exp                      [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  mc_relax                             [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  mc_relax_after                       [string list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets n_mc_relax_after'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  mc_relax_opt                         [string, default gd]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  mc_reverse                           [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  mc_reverse_lambda                    [real, default 0.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  mc_species                           [string list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets mc_mu'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  mc_swaps                             [string list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets n_mc_swaps; sets species; sets mc_swaps_id'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  mc_types                             [string list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets n_mc_types'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  mc_write_xyz                         [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  n_mc_mu                              [integer, default 0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets mc_mu; sets mc_species; sets mc_mu_acceptance'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  n_mc_relax_after                     [integer, default 0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets mc_relax_after'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  n_mc_swaps                           [integer, default 0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets mc_swaps; sets mc_swaps_id'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  n_mc_types                           [integer, default 0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets mc_types; sets mc_acceptance'
         write (*, '(A)') ''
      end if

!     ---- Van der Waals
      if (every .or. .not. gap_only) then
         write (*, '(A)') '=== VAN DER WAALS ==='
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  do_nnls                              [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  mbd_correction_freq                  [integer, default 100]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  poly_cut_xmax                        [real, default 10.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  poly_cut_xmin                        [real, default 3.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  print_vdw_forces                     [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_2b_rcut                          [real, default 15.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_2b_rcut2                         [real, default 8.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_alpha0_ref                       [real list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_buffer                           [real, default 1.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_buffer_inner                     [real, default 0.5]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_c6_ref                           [real list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_d                                [real, default 20.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_d_mbd                            [real, default 6.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_hirsh_grad                       [logical, default true]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_loc_rcut                         [real, default 5.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_mbd_cent_appr                    [logical, default true]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_mbd_grad                         [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_mbd_nfreq                        [integer, default 11]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_mbd_norder                       [integer, default 6]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_mbd_rcut                         [real, default 15.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_mbd_rcut2                        [real, default 8.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_omega_ref                        [real, default 1.3]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_polynomial                       [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_r0_ref                           [real list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_rcut                             [real, default 10.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_rcut_inner                       [real, default 0.5]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_scs_rcut                         [real, default 4.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_sr                               [real, default 0.94]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_sr_mbd                           [real, default 0.83]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  vdw_type                             [string, default none]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if

!     ---- Electrostatics
      if (every .or. .not. gap_only) then
         write (*, '(A)') '=== ELECTROSTATICS ==='
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  estat_damped                         [type(options_estat)]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  estat_damped_cosine                  [type(options_estat)]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  estat_dsf_alpha                      [real, default -1.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  estat_gsf                            [type(options_estat)]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  estat_inner_width                    [real, default 1.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  estat_method                         [string, default none]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  estat_rcut                           [real, default 10.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  estat_rcut_inner                     [real, default 4.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  estat_self_energy_correction         [type(options_estat)]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  estat_sp                             [type(options_estat)]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  estat_tsf                            [type(options_estat)]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  print_estat_forces                   [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if

!     ---- Experimental data (MAD)
      if (every .or. .not. gap_only) then
         write (*, '(A)') '=== EXPERIMENTAL DATA (MAD) ==='
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  do_exp                               [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  do_nd                                [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets do_pair_distribution; sets do_structure_factor'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  do_pair_distribution                 [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  do_structure_factor                  [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets do_pair_distribution'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  do_xps                               [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  do_xrd                               [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets do_pair_distribution; sets do_structure_factor'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  exp_data_files                       [type(exp_data_container) list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets exp_energy_scales'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  exp_data_weights                     [type(exp_data_container) list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets exp_energy_scales'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  exp_energies                         [logical, default true]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets do_exp'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  exp_energy_scales                    [real list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets n_exp; sets exp_energy_scales_initial; sets'
         write (*, '(A)') '         exp_energy_scales_final'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  exp_energy_scales_final (or exp_energy_scales_end) [integer, default 0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  exp_forces                           [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets do_exp'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  exp_input_type                       [type(exp_data_container) list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets exp_energy_scales'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  exp_labels                           [type(exp_data_container) list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets exp_energy_scales; sets xps_idx; sets xrd_idx; sets'
         write (*, '(A)') '         valid_xrd; sets pair_distribution_partial; sets nd_idx; sets'
         write (*, '(A)') '         valid_nd; sets saxs_idx; sets pdf_idx; sets valid_pdf; sets'
         write (*, '(A)') '         sf_idx; sets valid_sf'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  exp_n_samples                        [type(exp_data_container) list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets exp_energy_scales'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  exp_similarity_type                  [string, default squared_diff]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  exp_weights_files                    [type(exp_data_container) list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets exp_energy_scales'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  n_exp                                [integer, default 0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets exp_data_files; sets exp_energy_scales; sets'
         write (*, '(A)') '         exp_energy_scales_initial; sets exp_energy_scales_final; sets'
         write (*, '(A)') '         do_exp'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  nd_n_samples                         [integer, default 200]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets xrd_n_samples; sets structure_factor_n_samples'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  nd_output                            [string, default xrd]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets xrd_output'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  nd_rcut                              [real, default 4.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  nd_wavelength                        [real, default 1.5405981]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  pair_distribution_kde_sigma          [real, default 0.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  pair_distribution_n_samples          [integer, default 200]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  pair_distribution_output             [string, default pdf]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  pair_distribution_partial            [logical, default true]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  pair_distribution_rcut               [real, default 4.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  q_range_max                          [real, default 5.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  q_range_min                          [real, default 1.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  q_units                              [string, default q]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  r_range_max                          [real, default 5.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  r_range_min                          [real, default 1.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  sf_output                            [string, default xrd]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  structure_factor_from_pdf            [logical, default true]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  structure_factor_matrix              [logical, default true]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  structure_factor_matrix_forces       [logical, default true]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  structure_factor_n_samples           [integer, default 200]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  structure_factor_window              [logical, default true]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  xps_e_max                            [real, default 300.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  xps_e_min                            [real, default 280.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  xps_force_type                       [string, default similarity]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  xps_n_samples                        [integer, default 200]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  xps_sigma                            [real, default 0.4]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  xrd_alpha                            [real, default 1.01]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  xrd_damping                          [real, default 0.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  xrd_iwasa                            [logical, default true]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  xrd_method                           [string, default xrd]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  xrd_n_samples                        [integer, default 200]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets structure_factor_n_samples'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  xrd_output                           [string, default xrd]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  xrd_rcut                             [real, default 4.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  xrd_wavelength                       [real, default 1.5405981]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if

!     ---- Electronic stopping and EPH
      if (every .or. .not. gap_only) then
         write (*, '(A)') '=== ELECTRONIC STOPPING AND EPH ==='
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  adapt_emax                           [real, default 1.0e1]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  adapt_tmax                           [real, default 1.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  adapt_tmin                           [real, default 1.0e-3]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  adapt_tstep_interval                 [integer, default 1]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  adapt_xmax                           [real, default 1.0e-2]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  adaptive_time                        [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  eel_cut                              [real, default 1.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  eel_freq_out                         [integer, default 1]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  electronic_stopping                  [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  eph_betafile                         [string, default NULL]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  eph_box_limits                       [real(6), default [-100.0, 100.0, -100.0, 100.0, ...]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets in_x0; sets in_x1; sets in_y0; sets in_y1; sets in_z0;'
         write (*, '(A)') '         sets in_z1'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  eph_c_e                              [real, default 1.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  eph_e_prev_time                      [real, default 0.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  eph_fdm_option                       [integer, default 1]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  eph_fdm_steps                        [integer, default 1]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  eph_freq_mesh_tout                   [integer, default 1]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  eph_freq_tout                        [integer, default 1]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  eph_friction_option                  [integer, default 1]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  eph_gsx                              [integer, default 1]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  eph_gsy                              [integer, default 1]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  eph_gsz                              [integer, default 1]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  eph_kappa_e                          [real, default 1.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  eph_md_last_step                     [integer, default 0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  eph_md_prev_time                     [real, default 0.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  eph_random_option                    [integer, default 1]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  eph_rho_e                            [real, default 1.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  eph_ti_e                             [real, default 300.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  eph_tinfile                          [string, default NULL]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  eph_toutfile                         [string, default NULL]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  estop_filename                       [string, default NULL]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  model_eph                            [integer, default 1]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  nonadiabatic_processes               [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if

!     ---- Local properties
      if (every .or. .not. gap_only) then
         write (*, '(A)') '=== LOCAL PROPERTIES ==='
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  compute_local_properties'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  core_pot_buffer                      [real, default 1.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  core_pot_cutoff                      [real, default 1.e10]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  n_local_properties                   [integer, default 0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets write_local_properties; sets compute_local_properties'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  print_lp_forces                      [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if

!     ---- Output
      if (every .or. .not. gap_only) then
         write (*, '(A)') '=== OUTPUT ==='
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  print_progress                       [logical, default true]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  write_exp                            [logical, default true]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  write_fixes                          [logical, default true]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  write_forces                         [logical, default true]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  write_hirshfeld_v                    [logical, default true]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  write_local_energies                 [logical, default true]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  write_local_properties'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  write_lv                             [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  write_masses                         [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  write_nd                             [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  write_pair_distribution              [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  write_pressure                       [logical, default true]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  write_stress                         [logical, default true]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  write_structure_factor               [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  write_thermo                         [integer, default 1]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  write_velocities                     [logical, default true]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  write_virial                         [logical, default true]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  write_xrd                            [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  write_xyz                            [integer, default 0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if

!     ---- GPU
      if (every .or. .not. gap_only) then
         write (*, '(A)') '=== GPU ==='
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  gpu_batched                          [logical, default true]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  gpu_low_memory                       [logical, default true]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  gpu_max_batch_size                   [real, default 1.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  gpu_n_batches                        [integer, default 1]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. .not. gap_only) then
         write (*, '(A)') '  n_batches                            [integer, default 0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if

!  ======== the potential (.gap) file
      if (every .or. gap_only) then
         write (*, '(A)') ''
         write (*, '(A)') '##### KEYWORDS FOR THE POTENTIAL (.GAP) FILE #####'
         write (*, '(A)') ''
         write (*, '(A)') '  The fitted potential, named by pot_file in the input file. It is a'
         write (*, '(A)') '  sequence of blocks, each opened by gap_beg <descriptor> and closed by'
         write (*, '(A)') '  gap_end, holding one keyword = value per line. gap_beg and gap_end are'
         write (*, '(A)') '  file syntax rather than settings and are not listed below. Unlike the'
         write (*, '(A)') '  input file, a keyword the block does not recognise is skipped in'
         write (*, '(A)') '  silence, so a misspelling here shows up as a wrong answer rather than an'
         write (*, '(A)') '  error. These files are written by the fitting code, not by hand.'
         write (*, '(A)') ''
      end if

!     ---- soap_turbo
      if (every .or. gap_only) then
         write (*, '(A)') '=== SOAP_TURBO ==='
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  alphas_sparse                        [string]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  amplitude_scaling                    [real list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  atom_sigma_r                         [real list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  atom_sigma_r_scaling                 [real list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  atom_sigma_t                         [real list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  atom_sigma_t_scaling                 [real list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  basis                                [string, default poly3]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  buffer                               [real list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  central_species                      [integer, default 0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  central_weight                       [real list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  compress_mode                        [string, default none]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  compress_soap                        [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  delta                                [real, default 1.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  desc_sparse                          [string]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  dipole_model                         [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  file_compress_soap                   [string, default none]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  global_scaling                       [real list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  has_local_properties                 [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  has_vdw                              [logical, default false]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets has_local_properties; sets n_local_properties; sets'
         write (*, '(A)') '         vdw_index'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  l_max                                [integer]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  local_property_alphas                [type(local_property_soap_turbo) list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets n_local_properties'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  local_property_deltas                [type(local_property_soap_turbo) list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  local_property_labels                [type(local_property_soap_turbo) list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets n_local_properties; sets has_vdw; sets vdw_index; sets'
         write (*, '(A)') '         has_core_electron_be; sets core_electron_be_index; sets'
         write (*, '(A)') '         has_charges'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  local_property_qs                    [type(local_property_soap_turbo) list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets n_local_properties'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  local_property_v0s                   [type(local_property_soap_turbo) list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  local_property_zetas                 [integer, default 0& !  compress_P_nonzero]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  n_local_properties                   [integer, default 0& !  compress_P_nonzero]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  n_max                                [integer]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets alpha_max'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  n_species                            [integer]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets nf; sets rcut; sets buffer; sets atom_sigma_r; sets'
         write (*, '(A)') '         atom_sigma_t; sets atom_sigma_r_scaling; sets'
         write (*, '(A)') '         atom_sigma_t_scaling; sets amplitude_scaling; sets'
         write (*, '(A)') '         central_weight; sets global_scaling; sets n_max; sets species'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  nf                                   [real list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  radial_enhancement                   [integer, default 0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  rcut                                 [real list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') '      -> sets rcut_max'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  scaling_mode                         [string, default polynomial]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  species                              [string list]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  vdw_alphas'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  vdw_delta'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  vdw_qs'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  vdw_v0'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  vdw_zeta'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  zeta                                 [real, default 2.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if

!     ---- distance_2b
      if (every .or. gap_only) then
         write (*, '(A)') '=== DISTANCE_2B ==='
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  Z1 (or z1, species1)                 [string]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  Z2 (or z2, species2)                 [string]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  alphas_sparse                        [string]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  delta                                [real, default 1.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  desc_sparse                          [string]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  rcut                                 [real]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  sigma                                [real, default 1.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if

!     ---- angle_3b
      if (every .or. gap_only) then
         write (*, '(A)') '=== ANGLE_3B ==='
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  Z1 (or z1, species1)                 [string]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  Z2 (or z2, species2)                 [string]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  Z_center (or z_center, species_center) [string]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  alphas_sparse                        [string]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  delta                                [real, default 1.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  desc_sparse                          [string]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  kernel_type                          [string, default exp]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  rcut                                 [real]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  sigma                                [real(1:3), default 1.0]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if

!     ---- core_pot
      if (every .or. gap_only) then
         write (*, '(A)') '=== CORE_POT ==='
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  Z1 (or z1, species1)                 [string]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  Z2 (or z2, species2)                 [string]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if
      if (every .or. gap_only) then
         write (*, '(A)') '  core_pot_file                        [string]'
         write (*, '(A)') '      (undocumented)'
         write (*, '(A)') ''
      end if

   end subroutine print_keyword_help

end module keyword_help
